In [1]:
import pandas as pd
s=pd.Series([10,20,30],index=["a","b","c"])
print(s)

data={
    "Name":["Alice","Bob","John Dea"],
    "Age":[25,56,32]
}
df=pd.DataFrame(data)
print(df)

url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
col_name=["sepal_length","sepal_width","petal_length","petal_width","class"]
df=pd.read_csv(url,header=None,names=col_name,index_col=False)
print(df.head())
print(df.info())

a    10
b    20
c    30
dtype: int64
       Name  Age
0     Alice   25
1       Bob   56
2  John Dea   32
   sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   class         150 non-null    str    
dtypes: float64(4), str(1)
memory usage: 6.0 KB
None


Pandas vs NumPy - Which one to use and When?
Dimension > 2: Use NumPy
Use NumPy (ndarray) when your 2-D data is essentially a numeric matrix and you need fast, memory-efficient numerical work (linear algebra, broadcasting, heavy elementwise operations).
Use pandas (DataFrame) when your 2-D data is a table i.e., columns with names, mixed dtypes, missing values, need for grouping/joins/time-series/CSV/Excel IO or easy selection by column name

Will Pandas work when data is larger than memory?
Since Pandas loads the entire dataset into memory. if data is larger than the main memory Here are practical approaches:
1. Dask: A library that extends pandas with parallel computing and chunked processing.
2. Polars: A fast DataFrame library written in Rust, with lazy execution and streaming.
3. "PySpark:" A distributed big-data engine. PySpark splits the dataset into chunks (partitions) and processes them sequentially or in parallel - only a small chunk is in memory at a time.

1. What is a DataFrame?
A DataFrame is a two-dimensional, labeled data structure that stores data in rows and columns, allowing each column to hold values of different data types. A data structure is a way of organizing, storing, and managing data in a computer so that it can be used efficiently.
It is designed for handling and analyzing structured (tabular) data efficiently.
A DataFrame is:
Two-dimensional: Data is arranged in rows and columns.
Labeled: Each row has an index (like row numbers), and each column has a name.
Flexible: Can store different data types in different columns (numbers, text, dates, etc.).
Mutable: You can change, add, or delete rows and columns anytime.

In [ ]:
import pandas as pd
import numpy as np

data={
    'Name':['Amit','Anand','Akash'],
    'Age':[25,26,28],
    'City':['Mumbai','Delhi','Patna']
}
df=pd.DataFrame(data)
print(df.head())
df1=pd.DataFrame(data,index=None,columns=None,dtype=None,copy=False)
print(df1)
data=[
    ['Amit', 25, 'Mumbai'],
    ['Anand', 28, 'Delhi'],
    ['Akash', 30, 'Patna']
]
df=pd.DataFrame(data,columns=['Name','Age','City'])
print(df)
arr=np.array([['Amit', 25, 'Mumbai'],
['Anand', 28, 'Delhi'],
['Akash', 30, 'Patna']])
print(np.shape(arr))

name=pd.Series(['Amit','Anand','Akash'])
age=pd.Series([25,26,28])
city=pd.Series(['Mumbai','Delhi','Patna'])

df=pd.DataFrame({'Name':name,'Age':age,'City':city})
print(df)

    Name  Age    City
0   Amit   25  Mumbai
1  Anand   26   Delhi
2  Akash   28   Patna
    Name  Age    City
0   Amit   25  Mumbai
1  Anand   26   Delhi
2  Akash   28   Patna
    Name  Age    City
0   Amit   25  Mumbai
1  Anand   28   Delhi
2  Akash   30   Patna
(3, 3)
    Name  Age    City
0   Amit   25  Mumbai
1  Anand   26   Delhi
2  Akash   28   Patna


From CSV / EXCEL FILE

In [17]:
! pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------

In [18]:


df=pd.read_csv("dummy_data_csv.csv")
print(df)
df=pd.read_csv("dummy_data_tsv.tsv",sep='\t')
print(df)
df=pd.read_excel("dummy_data_excel.xlsx")
print(df.head())

      Name  Age     City  Salary
0     Amit   25    Patna   70000
1    Akash   30  Lucknow   80000
2     Aman   35    Delhi   75000
3   Manish   28   Jaipur   72000
4  Peeyush   32   Ranchi   78000
      Name  Age     City  Salary
0     Amit   25    Patna   70000
1    Akash   30  Lucknow   80000
2     Aman   35    Delhi   75000
3   Manish   28   Jaipur   72000
4  Peeyush   32   Ranchi   78000
      Name  Age     City  Salary
0     Amit   25    Patna   70000
1    Akash   30  Lucknow   80000
2     Aman   35    Delhi   75000
3   Manish   28   Jaipur   72000
4  Peeyush   32   Ranchi   78000


From URL

In [19]:
url="https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
df=pd.read_csv(url)
print(df.head())

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


In [ ]:
url="https://jsonplaceholder.typicode.com/users"
df=pd.read_json(url)
print(df.head())

   id              name   username                      email  \
0   1     Leanne Graham       Bret          Sincere@april.biz   
1   2      Ervin Howell  Antonette          Shanna@melissa.tv   
2   3  Clementine Bauch   Samantha         Nathan@yesenia.net   
3   4  Patricia Lebsack   Karianne  Julianne.OConner@kory.org   
4   5  Chelsey Dietrich     Kamren   Lucio_Hettinger@annie.ca   

                                             address                  phone  \
0  {'street': 'Kulas Light', 'suite': 'Apt. 556',...  1-770-736-8031 x56442   
1  {'street': 'Victor Plains', 'suite': 'Suite 87...    010-692-6593 x09125   
2  {'street': 'Douglas Extension', 'suite': 'Suit...         1-463-123-4447   
3  {'street': 'Hoeger Mall', 'suite': 'Apt. 692',...      493-170-9623 x156   
4  {'street': 'Skiles Walks', 'suite': 'Suite 351...          (254)954-1289   

         website                                            company  
0  hildegard.org  {'name': 'Romaguera-Crona', 'catchPhrase': 'Mu

In [21]:
! pip install lxml


Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/4.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.1 MB ? eta -:--:--
   ------- -------------------------------- 0.8/4.1 MB 5.9 MB/s eta 0:00:01
   ------------------------- -------------- 2.6/4.1 MB 8.3 MB/s eta 0:00:01
   ---------------------------------------- 4.1/4.1 MB 9.7 MB/s  0:00:00


In [33]:
! pip install requests


Defaulting to user installation because normal site-packages is not writeable

   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   -------------------------------- ------- 4/5 [requests]
   ---------------------------------------- 5/5 [requests]



In [40]:
url="https://en.wikipedia.org/wiki/Indian_Institutes_of_Information_Technology"
tables = pd.read_html(url)
len(tables)

HTTPError: HTTP Error 403: Forbidden

Basic Operation in Pandas


In [6]:
import pandas as pd

data={
    'Name':['Amit','Anand','Akash'],
    'Age':[25,26,28],
    'City':['Mumbai','Delhi','Patna']
}
df=pd.DataFrame(data)
print(df)
print(df.shape)
print(len(df))
print(df.dtypes)

    Name  Age    City
0   Amit   25  Mumbai
1  Anand   26   Delhi
2  Akash   28   Patna
(3, 3)
3
Name      str
Age     int64
City      str
dtype: object


In [ ]:
# reduce memory consumed for age attribute
df['Age']=df['Age'].astype('int32')
df['City']=df['City'].astype('string')
print(df.dtypes)
df.columns
df.index


Name       str
Age      int32
City    string
dtype: object


RangeIndex(start=0, stop=3, step=1)

In [36]:
from numpy.random import randint as ri
data=ri(20,30,25).reshape(5,5)
print(data)
row_label=['A','B','C','D','E']
col_name=['U','V','W','X','Y']
df=pd.DataFrame(data,index=row_label,columns=col_name)
print(df)
print(df.describe())
print(df.index)
print(df.columns)
df2=df
print(df2)

[[28 22 21 21 27]
 [27 26 23 25 26]
 [24 29 29 22 24]
 [21 23 29 21 26]
 [20 27 26 28 29]]
    U   V   W   X   Y
A  28  22  21  21  27
B  27  26  23  25  26
C  24  29  29  22  24
D  21  23  29  21  26
E  20  27  26  28  29
               U          V          W         X         Y
count   5.000000   5.000000   5.000000   5.00000   5.00000
mean   24.000000  25.400000  25.600000  23.40000  26.40000
std     3.535534   2.880972   3.577709   3.04959   1.81659
min    20.000000  22.000000  21.000000  21.00000  24.00000
25%    21.000000  23.000000  23.000000  21.00000  26.00000
50%    24.000000  26.000000  26.000000  22.00000  26.00000
75%    27.000000  27.000000  29.000000  25.00000  27.00000
max    28.000000  29.000000  29.000000  28.00000  29.00000
Index(['A', 'B', 'C', 'D', 'E'], dtype='str')
Index(['U', 'V', 'W', 'X', 'Y'], dtype='str')
    U   V   W   X   Y
A  28  22  21  21  27
B  27  26  23  25  26
C  24  29  29  22  24
D  21  23  29  21  26
E  20  27  26  28  29


In [20]:
print(df[['X','Y']])

    X   Y
A  24  24
B  25  20
C  22  24
D  27  29
E  25  26


Delete Row and Column

In [38]:
print(df.drop('B'))
print(df.drop('X',axis=1))
df1=df
# df1.drop('U',axis=1,inplace=True)


    U   V   W   X   Y
A  28  22  21  21  27
C  24  29  29  22  24
D  21  23  29  21  26
E  20  27  26  28  29
    U   V   W   Y
A  28  22  21  27
B  27  26  23  26
C  24  29  29  24
D  21  23  29  26
E  20  27  26  29


Selecting/Indexing Rows

In [53]:
df.head()
df2.head()
print(df2.loc['A'])
print(df2.iloc[2])
print(df2)
print(df2.loc[['A','D']])
print(df2.iloc[[1,4]])
print(df2.loc['A':'C'])
print(df2.iloc[1:3])

U    28
V    22
W    21
X    21
Y    27
Name: A, dtype: int32
U    24
V    29
W    29
X    22
Y    24
Name: C, dtype: int32
    U   V   W   X   Y
A  28  22  21  21  27
B  27  26  23  25  26
C  24  29  29  22  24
D  21  23  29  21  26
E  20  27  26  28  29
    U   V   W   X   Y
A  28  22  21  21  27
D  21  23  29  21  26
    U   V   W   X   Y
B  27  26  23  25  26
E  20  27  26  28  29
    U   V   W   X   Y
A  28  22  21  21  27
B  27  26  23  25  26
C  24  29  29  22  24
    U   V   W   X   Y
B  27  26  23  25  26
C  24  29  29  22  24


In [60]:
# Subnetting
print(df2.loc['A','Y'])
print(df2.iloc[0,2])
df2

27
21


,U,V,W,X,Y
A,28,22,21,21,27
B,27,26,23,25,26
C,24,29,29,22,24
D,21,23,29,21,26
E,20,27,26,28,29


In [63]:
# adding row to a dataframe
df2.loc['F']=[34,56,78,56,89]
print(df2)

    U   V   W   X   Y
A  28  22  21  21  27
B  27  26  23  25  26
C  24  29  29  22  24
D  21  23  29  21  26
E  20  27  26  28  29
F  34  56  78  56  89


In [81]:
# split
# adding new col
# rename the index of a dataframe
# Rename the col of a dataframe 
import numpy as np
matrix_data = np.matrix('22,160,70;42,170,80;30,175,90;35,160,70;25,140,70')
row_labels = ['A','B','C','D','E']
column_headings = ['Age', 'Height', 'Weight'] # 'Height(Cm)', 'Weight(Kg)
df=pd.DataFrame(matrix_data,index=row_label,columns=column_headings)
print(df)
df.loc['F']=[21,170,60]
df['BMI']=df['Weight']/(df['Height']/100)**2
df['Proffession']="Student Teacher Engineer Doctor Nurse Student".split()
df.columns=['age', 'height', 'weight','bmi','proffession']
df.index=[0,1,2,3,4,5]


   Age  Height  Weight
A   22     160      70
B   42     170      80
C   30     175      90
D   35     160      70
E   25     140      70


In [98]:
df[df['height']>160]
df2.reset_index(inplace=True)